name: 'playwright-slack-action'
description: 'Generate a detailed slack message for the playwright test result'
outputs:
  result:
    description: 'Result of the playwright command'
runs:
  using: 'node12'
  main: 'index.js'